server:
  port: 9094

spring:
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:3306/orderdb
    username: root
    password: root
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL57InnoDBDialect
    hibernate:
      ddl-auto: update
  application:
    name: ORDER-SERVICE
  config:
    import: "configserver:${CONFIG_SERVER_URL:http://localhost:9296}"
    #import: "configserver:http://${CONFIG_SERVER_URL:localhost}:9296"
    #import: configserver:http://localhost:9296
#  security:
#    oauth2:
#      resourceserver:
#        jwt:
#          issuer-uri: http://localhost:8080/realms/iod
#          jwk-set-uri: http://localhost:8080/auth/realms/my-realm/protocol/openid-connect/certs
#      client:
#        registration:
#          internal-client:
#            provider: iod
#            authorization-grant-type: client_credentials
#            grant-type: client_credentials
#            scopes: email, profile, offline_access
#            client-id: iod-rest-api
#            client-secret: 5NtAdnCptRpYxivVmz44ETi2086xuXsD
#        provider:
#          iod:
#            issuer-uri: http://localhost:8080/realms/iod

resilience4j:
  circuitbreaker:
    instances:
      external:
        event-consumer-buffer-size: 10
        failure-rate-threshold: 50
        minimum-number-of-calls: 5
        automatic-transition-from-open-to-half-open-enabled: true
        wait-duration-in-open-state: 5s
        permitted-number-of-calls-in-half-open-state: 3
        sliding-window-size: 10
        sliding-window-type: COUNT_BASED



#eureka:
#  instance:
#    prefer-ip-address: true
#  client:
#    fetch-registry: true
#    register-with-eureka: true
#    service-url:
#      defaultZone: ${EUREKA_SERVER_ADDRESS:http://localhost:8761/eureka}
